version: 'build {build}'

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"
      PYTHON_WIN: "win32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"
      PYTHON_WIN: "win_amd64"

install:
  - ps: $env:Path = "$env:PYTHON;$env:PYTHON\Scripts;$env:Path"

  # Check that we have the expected version and architecture for Python
  - ps: python --version
  - ps: python -c "import struct; print(struct.calcsize('P') * 8)"

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - ps: pip install --disable-pip-version-check --user --upgrade pip

  # Install dependencies. Get lxml from bundled wheel instead of compiling,
  # because it requires some extra steps that aren't worth it.
  - ps: pip install wheel
  - ps: pip install "bin\lxml-3.6.0-cp35-cp35m-$env:PYTHON_WIN.whl"
  - ps: pip install -r requirements.txt

  # Install pandoc for making a .docx version of the markdown documentation.
  # tip per http://code.metager.de/source/xref/mono/appveyor.yml
  - ps: choco install pandoc -y
  - ps: $env:Path = "C:\Program Files (x86)\Pandoc;$env:Path"
  - ps: $env:Path = "C:\cygwin\bin;$env:Path"
  - ps: sh generate_docx.sh
  - ps: ls docs

# Build not required for test, only have to build things after test.
build: off

test_script:
  # Run the project tests
  - ps: python setup.py test

after_test:
  # Create python packages for the project.
  - ps: python setup.py sdist
  - ps: python setup.py bdist_wheel

  # Build the pyinstaller package.
  - ps: pyinstaller gui_spec.spec
  - ps: ls dist

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*
    name: dist-$(PYTHON_WIN)
  - path: dist\gui
    name: gui-$(PYTHON_WIN)

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: >
    AppVeyor build. Includes Python source dist, wheel, and self-contained
    executable builds of the GUI app for Windows 32-bit and 64-bit.
  provider: GitHub
  auth_token:
    secure: NtPZXcWIFDe2fOnxFYxDAlnbiVRuClb3A+wlkdB0iXBuyEbgIQmtRRdHSP4jyacd
  artifact: dist-$(PYTHON_WIN),gui-$(PYTHON_WIN)
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
